//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonGiaoHang
    {
        public int MaDGH { get; set; }
        public int MaDH { get; set; }
        public int MaTaiXe { get; set; }
        public int MaXe { get; set; }
        public string ThuTuXepHang { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual TaiXe TaiXe { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
