//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.DonGiaoHangs = new HashSet<DonGiaoHang>();
            this.MaVaches = new HashSet<MaVach>();
            this.NhomDonHangs = new HashSet<NhomDonHang>();
            this.PhieuThus = new HashSet<PhieuThu>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaLH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string NoiNhanHang { get; set; }
        public string NoiGiaoHang { get; set; }
        public Nullable<System.DateTime> NgayNhanHang { get; set; }
        public Nullable<System.DateTime> NGayGiaoHang { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public Nullable<bool> QuaHanTT { get; set; }
    
        public virtual ICollection<DonGiaoHang> DonGiaoHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual LoaiHang LoaiHang1 { get; set; }
        public virtual ICollection<MaVach> MaVaches { get; set; }
        public virtual ICollection<NhomDonHang> NhomDonHangs { get; set; }
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
    }
}
