//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaVach
    {
        public int MaVach1 { get; set; }
        public int MaDH { get; set; }
        public int MaNhom { get; set; }
        public int SoLuong { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
