//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi
    {
        public int MaPhieuChi { get; set; }
        public Nullable<System.DateTime> NgayChi { get; set; }
        public string NguoiNhan { get; set; }
        public decimal TienChi { get; set; }
        public string ĐiaDiem { get; set; }
        public string LyDo { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
