//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuCongNo
    {
        public int MaPhieuCN { get; set; }
        public int MaDH { get; set; }
        public int MaKH { get; set; }
        public int MaPhieuThu { get; set; }
        public Nullable<decimal> TienNo { get; set; }
    }
}
