//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public int MaPhieuThu { get; set; }
        public int MaDH { get; set; }
        public string KhachHang { get; set; }
        public decimal TienThu { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public string ĐiaDiem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
