//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemChamCong
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiXe
    {
        public TaiXe()
        {
            this.DonGiaoHangs = new HashSet<DonGiaoHang>();
            this.NhomDonHangs = new HashSet<NhomDonHang>();
        }
    
        public int MaTaiXe { get; set; }
        public string TenTaiXe { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<DonGiaoHang> DonGiaoHangs { get; set; }
        public virtual ICollection<NhomDonHang> NhomDonHangs { get; set; }
    }
}
